### ISSUE TITLE
## Group Manager

### ISSUE THREAD

**Issue by devstepien** [Andy9822/Instant-Messenger-Cpp#15]
- Lista de threads (gerenciador de comunicação matar a thread).
- Arquivo de persistência. 
- Thread que fica ouvindo o grup e fazando broadcast.

**Comment by Andy9822** [comment]
Rascunho do problema de consumidor dormir ou acordar dependendo se existem recursos a consumir e sincronização
![board](https://user-images.githubusercontent.com/19315023/95000419-f065df80-05c0-11eb-8210-45f6ee92bf8d.png)

**Comment by devstepien** [comment]
![image](https://user-images.githubusercontent.com/23477064/95002047-411c0f00-05a6-11eb-94fa-4fa4b4df488a.png)
