### ISSUE TITLE
Message Manager

### ISSUE THREAD

**Issue by devstepien** [Andy9822/Instant-Messenger-Cpp#4]
- Order messages when sending messages to users.

**Comment by devstepien** [comment]
This module will:
- Make a CRUD for the messages that are getting to the system :file_cabinet: 
- Send the messages to the communication layer as a bridge between the groups and communication layers.

**Comment by devstepien** [comment]
Created one class called user so it will keep the information for the user and also maintain the sockets associated with the users.

**Comment by devstepien** [comment]
Create class MessageManger to take care of the messages. 
Create FileSystemManager to persist the messages.

Since the filesystem will be handling the messages and the persistence in the database, when it is executed we need to have a critic section for the group file.

- I'm thinking of having one instance of file manager per group. So we can use a binary semaphore to protect each critical section. 

@Andy9822 , @cassiano probably this will concern you. The best way for doing that, in my opinion, is to have on group manager a list of group objects. Each group object should have one instance of messageManager. With that, we can have a critic section protected for the calls of the FileSystem.

**Comment by Andy9822** [comment]
lgtm 
The only part I'm not completely sure is about having 1 instance of file manager per group.
We could have 1 FileManager for the entire system and then every MessageManager notifies when they want the FileManager to modify a given file with a given string.

Buf if it's easier to have multiple instances of FileManagers to avoid complexity, I'm in

@gabriel-inf

**Comment by cassianojaeger** [comment]
Yea, I'm not completely sure about the approach, but if this is the simplest way of doing this, it is ok. Also we can discuss this during the week.
